name: Deploy Backend to VPS

on:
  push:
    branches:
      - main

env:
  SSH_PORT: 1999
  SSH_USERNAME: ${{ secrets.SSH_USER }}
  SSH_SERVER: ${{ secrets.SSH_HOST }}
  SSH_OPTIONS: -o StrictHostKeyChecking=yes
  DEST_DIR: /var/www/clients/client0/web3/web/symblog # Répertoire de destination
  HTACCESS_PATH: /var/www/clients/client0/web3/web/symblog/public/ # Chemin du fichier .htaccess
  BACKUP_DIR: /var/www/clients/client0/web3/web/backups # Répertoire où seront stockées les sauvegardes
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DATABASE_NAME: ${{ secrets.DATABASE_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          echo "Configuring SSH..."
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          echo "Host deploy
            HostName $SSH_SERVER
            User $SSH_USERNAME
            Port $SSH_PORT
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking yes" > ~/.ssh/config

          # Configuration spécifique pour GitHub
          #echo "Host github.com
          #  HostName github.com
          #  User git
          #  IdentityFile ~/.ssh/vps_git_clone
          #  IdentitiesOnly yes
          #  PreferredAuthentications publickey" >> ~/.ssh/config

          ssh-keyscan -H -p 1999 $SSH_SERVER >> ~/.ssh/known_hosts
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts

          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/known_hosts
          chmod 600 ~/.ssh/config

      - name: Test SSH Connection
        run: ssh deploy "echo 'Connexion SSH réussie !'"

      - name: Enable maintenance mode
        run: |
          echo "Activating maintenance mode..."
          ssh deploy << 'EOF'
          mv $HTACCESS_PATH/.htaccess $HTACCESS_PATH/.htaccess.bak
          mv $HTACCESS_PATH/.htaccess.maintenance $HTACCESS_PATH/.htaccess
          EOF

      #- name: Reload Apache
      #  run: |
      #    echo "Reloading Apache..."
      #    ssh deploy "sudo systemctl reload apache2"

      - name: sleep
        run: sleep 5

      - name: Backup Database
        run: |
          echo "Backing up database..."
          ssh deploy mysqldump -u ${DB_USER} -p'${DB_PASSWORD}' ${DATABASE_NAME} > $BACKUP_DIR/db_backup_$(date +%F_%T).sql

      - name: Backup Source Code and Templates
        run: |
          echo "Backing up src/ and templates/..."
          ssh deploy << 'EOF'
          tar -czf $BACKUP_DIR/src_templates_backup_$(date +%F_%T).tar.gz -C $DEST_DIR src templates
          EOF

      - name: Deploy Application with Rsync
        run: |
          echo "Deploying application..."
          rsync -avz --exclude='var/' --exclude='vendor/' --exclude='cache/' --exclude='.env.local' --exclude='.env' ./ deploy:$DEST_DIR/

      - name: Validate Deployment
        run: |
          echo "Checking if application is running..."
          RESPONSE=$(curl -L -s -o /dev/null -w "%{http_code}" https://testartep.org/symblog)
          if [[ "$RESPONSE" -ne 200 ]]; then
            echo "Application is not responding! Rolling back..."
            exit 1
          fi
          echo "Deployment successful!"

      - name: Clear cache and optimize autoload
        run: |
          echo "Clearing Symfony cache..."
          ssh deploy << 'EOF'
          cd $DEST_DIR
          php bin/console cache:clear
          php bin/console cache:warmup
          composer dump-autoload --optimize
          EOF

      - name: Check and install Composer dependencies
        run: |
          echo "Checking Composer dependencies..."
          ssh deploy << 'EOF'
          cd $DEST_DIR
          git fetch --unshallow || true
          if git diff --name-only origin/main | grep -q "composer.lock"; then
            echo "Composer.lock changed, installing dependencies..."
            composer install --no-dev --optimize-autoloader
          else
            echo "No Composer changes detected, skipping install."
          fi
          EOF

      - name: Run Doctrine migrations if necessary
        run: |
          echo "Checking for pending migrations..."
          ssh deploy << 'EOF'
          cd $DEST_DIR
          if php bin/console doctrine:migrations:status -no-ansi | grep -q "New Migrations"; then
            echo "New migrations found, running migrations..."
            php bin/console doctrine:migrations:migrate --no-interaction
          else
            echo "No new migrations detected."
          fi
          EOF

      #- name: sleep
      #  run: sleep 30

      - name: Rollback Source Code and Templates
        if: failure()
        run: |
          echo "Rolling back src/ and templates/..."
          ssh deploy << 'EOF'
          tar -xzf $(ls -t $BACKUP_DIR/src_templates_backup_*.tar.gz | head -n 1) -C $DEST_DIR
          EOF

      - name: Disable maintenance mode
        if: always()
        run: |
          echo "Disabling maintenance mode..."
          ssh deploy << 'EOF'
          mv $HTACCESS_PATH/.htaccess $HTACCESS_PATH/.htaccess.maintenance
          mv $HTACCESS_PATH/.htaccess.bak $HTACCESS_PATH/.htaccess
          EOF

      #- name: sleep
      #  run: sleep 5

      #- name: Reload Apache
      #  run: |
      #    echo "Reloading Apache..."
      #    ssh deploy "sudo systemctl reload apache2"
