name: Deploy Backend to VPS

on:
  push:
    branches:
      - main

env:
  SSH_PORT: 1999
  SSH_USERNAME: ${{ secrets.SSH_USER }}
  SSH_SERVER: ${{ secrets.SSH_HOST }}
  SSH_OPTIONS: -o StrictHostKeyChecking=yes
  DEST_DIR: /var/www/clients/client0/web3/web/symblog
  HTACCESS_PATH: /var/www/clients/client0/web3/web/symblog/public/
  BACKUP_DIR: /var/www/clients/client0/web3/web/backups
  DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
  DATE: date +%F_%T

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches full history for accurate comparisons

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          cat > ~/.ssh/config << EOF
          Host deploy
            HostName $SSH_SERVER
            User $SSH_USERNAME
            Port $SSH_PORT
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking yes
          EOF

          ssh-keyscan -H -p $SSH_PORT $SSH_SERVER >> ~/.ssh/known_hosts
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts

          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/known_hosts ~/.ssh/config

      - name: Test SSH Connection
        run: ssh deploy "echo 'SSH connection successful!'"

      - name: Enable maintenance mode
        run: |
          ssh deploy << EOF
          if [ -f "$HTACCESS_PATH.htaccess" ]; then
            echo "Maintenance mode enabled."
            mv "$HTACCESS_PATH.htaccess" "$HTACCESS_PATH.htaccess.bak"
          fi
          if [ -f "$HTACCESS_PATH.htaccess.maintenance" ]; then
            echo "Maintenance mode already enabled."
            mv "$HTACCESS_PATH.htaccess.maintenance" "$HTACCESS_PATH.htaccess"
          fi
          EOF

      - name: Backup Database
        run: |
          ssh deploy << EOF
          mysqldump -u ${{ secrets.DB_USER }} -p"${{ secrets.DB_PASSWORD }}" $DATABASE_NAME > $BACKUP_DIR/db_backup_\$(date +%F_%T).sql
          EOF

      - name: Backup Source Code and Templates
        run: |
          ssh deploy << 'EOF'

          # Vérifier que les répertoires source existent
          if [ -d "/var/www/clients/client0/web3/web/symblog/src" ] && [ -d "/var/www/clients/client0/web3/web/symblog/templates" ]; then
            echo "Backing up src/ and templates/..."
            BACKUP_FILE="/var/www/clients/client0/web3/web/backups/src_templates_backup.tar.gz"
            tar -czf "$BACKUP_FILE" -C /var/www/clients/client0/web3/web/symblog src templates

            # Vérifier que la sauvegarde a été créée
            if [ -f "$BACKUP_FILE" ]; then
              echo "Backup created successfully"
            else
              echo "Backup failed to create"
              exit 1
            fi
          else
            echo "Source or templates directory not found"
            exit 1
          fi
          EOF

      - name: Deploy Application with Rsync
        run: |
          rsync -avz \
            --exclude='var/' \
            --exclude='vendor/' \
            --exclude='cache/' \
            --exclude='.env.local' \
            --exclude='.env' \
            ./ deploy:$DEST_DIR/

      - name: Validate Deployment
        run: |
          RESPONSE=$(curl -L -s -o /dev/null -w "%{http_code}" https://testartep.org/symblog
          if [[ "$RESPONSE" -ne 200 ]]; then
            echo "Application not responding. Rolling back..."
            exit 1
          fi
          echo "Deployment successful!"

      - name: Update Dependencies and Clear Cache
        run: |
          ssh deploy << 'EOF'
          cd "$DEST_DIR"
          php bin/console cache:clear
          php bin/console cache:warmup
          composer dump-autoload --optimize
          EOF

      - name: Check and Install Composer Dependencies
        run: |
          ssh deploy << 'EOF'
          cd "$DEST_DIR"
          git fetch --unshallow || true
          if git diff --name-only origin/main | grep -q "composer.lock"; then
            composer install --no-dev --optimize-autoloader
          fi
          EOF

      - name: Run Doctrine Migrations
        run: |
          ssh deploy << 'EOF'
          cd "$DEST_DIR"
          if php bin/console doctrine:migrations:status -no-ansi | grep -q "New Migrations"; then
            php bin/console doctrine:migrations:migrate --no-interaction
          fi
          EOF

      - name: Rollback Source Code and Templates
        if: failure()
        run: |
          ssh deploy << 'EOF'
          tar -xzf "$(ls -t "/var/www/clients/client0/web3/web/backups/src_templates_backup.tar.gz")" -C "$DEST_DIR"
          EOF

      - name: Disable Maintenance Mode
        if: always()
        run: |
          ssh deploy << EOF
          if [ -f "$HTACCESS_PATH.htaccess" ]; then
            echo "Maintenance mode disabled."
            mv "$HTACCESS_PATH.htaccess" "$HTACCESS_PATH.htaccess.maintenance"
          fi
          if [ -f "$HTACCESS_PATH.htaccess.bak" ]; then
            echo "Maintenance mode already disabled."
            mv "$HTACCESS_PATH.htaccess.bak" "$HTACCESS_PATH.htaccess"
          fi
          EOF

      - name: Cleanup Old Backups
        if: always()
        run: |
          ssh deploy << 'EOF'
          find "$BACKUP_DIR" -type f -name "db_backup_*" -mtime +7 -delete
          find "$BACKUP_DIR" -type f -name "src_templates_backup_*" -mtime +7 -delete
          EOF
